apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bazaarvoice
  namespace: uat
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  encryptedData:
    BV_URL: AgBGx/VdCb7btUAV1S+9TpvOp9uLiQdveZk6ZWqRxSQfiSe+W26VwHVmfv7GZ64LJbItP+12LS7YLW4NT74jCnJdwmfymezcBm9u9aUopqiWy1y4EfLtcD5VEJY1sJrAeQV6Mjs6ZerWUITOha0DFjvepxMXU71L4VoTHRNNT06GuQpFSyRLfGFiJ1mZkfUt5ruIWF+rRNFaPM5+tf9JEGppPjgNG0J3Mp66Jf6efBuwHqKJZAOKrqOd2nKkHuxesF0rldGTdk5C22shYY/lCwadWFOQrvWjUw+87HWt84jBT93WIgD33zuSYE4oBfdqQUQfD8fd/zPv0GHnTxNOuWlLAGiY3XJgwuBo0BtKGp1YtPlNyyPfm6oHzKDNbyOSyALyBu1Bv5yeaT8q00U1bEC9wu7kX+Ee5Qp+H3n6g2RVWCpwOSClz0LJ/S+S5g/j98JxPhYys0hGTDNQkwR1TNOUk92zbCu8eOE3p+N0m9v4KN744Qv3BvQcntPUegnkrkxzemsh7Ktf9tpsVgM/rI67hzariwUnn0fXKjpECAnQSx7c5Mlb3P19crbIAWExKJRiMaM9vlGXsXE3XzpIYjg/5MvBNjKm2mpB0+Jr/iaMaFZJhW48BUpUQR8whgX5dekcHX/QNIwP8I69JeAkNVmRSyXdcfdcxXYzmmX+40s0xcDbaYyjgJcN0E9J82bKePwgAbSDyKxOo2NDm4kV9C94oeA80EOP6F+NgqjjI4FaQvRH0vSh8CyIFdcgJ1DiKG/PetoKVINOlWDe6Ab2Jgp5A+500j0goZO+

