apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cordial
  namespace: uat
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  encryptedData:
    CORDIAL_AUTH_KEY: AgBQ9mh5RBGDSRwtHx0h+fgAJSemEYV1lxOphfN5iMwNpACqtKbyZzMUZd95vv+CZ6cEHNcc6VZaJRC/r4GqDLk0OLAEXBsq6H32vy9fWbKFjCDxve5fAETlJSBsb/+c4zEYKd09hdutxVsP8mRunbCe2RHI+lvgURFp7XjO4FoCpTaV1A4ovp6d/i6WzOQYe43LLarDZ7JvedgEsQXntIvQHPttspDJpK9He1rQGtfh4w7Vxr1aNcF/BcZaY0qvr7G4DEz+Baur0MkS/TVEu3rCM0ImtbYyuqcNZja1q9ZQ72KsLNZOwjU/eEFHfk9KQih0ZYaHgq7YQAEqi8FR+UbcfOn2joPnm00AuCTEH6PFQGuq9xP0tcpeTuBqTUmB+qeYt07mL/rrr2Vty6U2PdsH4fFYrX0r6//Gv0Du/p/R4nuUafssWasS0nBi1y8CZak4XDud9i32c/CJvouVCdWmB9gU9vbhhOurXSCRSzP2xPSNNJus1eNmcjK+S3Zd5ckvXC5BzqIMV4Dd5uJFISMmhDfrzYRV9PkLBlY8p6pEobYxPy3n/15sfG6FsZaYE/I98oXgOHF+Rr1f6TxnUz/NGr3TYVyCWGCdBbtq/0Le823O8w9MAsQsAY5ybavZ4XYUFtlMrJz6ggvVydL5blimc+Nc+TUurn3eAzAF+mSFsPFj2t+EWBDPsTuvcV5XsbKcR/8/kgRhaa0MmoEq9HdNrxhLVOU3pq0bTxMgMFUZT7gV95kCQbA1LhLqiez7Dx9BpHEty9jpQxC51RV+3K0ypiW0JOjutflmFge1d+Jpig==

