apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cordial
  namespace: uat
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  encryptedData:
    CORDIAL_AUTH_KEY: AgBfppEnRYEUX4TjGCfYSuC+WZA/Pn8+2E8R+eLb6Vc/Wvn8R4SOhOB19gBUIQA/OWzJwDoZiOiV/W7/AQ2NcnCY8tuCCZ+6mqnRHgBun3imVdxnRMzUoCwNK3aniZGf6M0wBzgD/AIE5N3F7719dWw5ojKLmD+dmUj5zlE+hFgCcA4vOoWnpaC69TvbIYgRSY4WfngGuxVjC4X2toMTxy5EazMN+89cmMw/J+stlamR/qADkB1sZQAm3Sd9BDthHJ+Ojnmkw+g39zxNOO9/11YHCEMXt8ck8NFI/hCysWSqgplc8RCHEuLXLwfyRdTidawfUkaGTqN/CBD17kK4/Tvhf8tPbgCeQuswBlaSi9mN62yH/SIY8jMaygoVpw8W4bEWT1S81dH35sMiPaHSvKSMboWtpK1q1IAjOQy47DmWVxvOS4qicYdllote56/5zehSxx+SPWKMSe1d/LlbgEyBVgaLUP2uu1mKjtClXAeN2VecM3ttAnU+JOf8Es9/Yz5flyIl0eiU34t1IfUAnZg95JZ/zMg6BL4QmxH4lIaqVZOyWPLG+5oEbn3V08Kxes0Cd7qSxTvdwgUeBU+oGO3Ms2/ZSbqAapJ0rmsLSbcnet/LmHJe4OrXDJcUd94VRfdWuhhg7kLY+ssp52jHQE8Wz81P30Q5wU0tcq4dfqbCpEdYwVNy6hqWqudobLYmpFJ9RFeWdaGpTQnmJ5ZF9IPvm+ojgdBb2CFiWWwhAbJz+3nzGHWHLqOgtKdJU7h5vDuSJeT+oczkt57fEqjX4SlPXt8aE0tw8d6k2WsSQyHYoA==

