apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dmr-web
  namespace: uat
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: lower-env-basic-auth
    # message to display with an appropiate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    # cert issuer
    certmanager.k8s.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{ .Files.Get "rewrite-rules.txt" | indent 6 }}
spec:
  tls:
  - hosts:
    - uat.dmr.upstart.team
    secretName: dmr-web-crt-uat
  rules:
  - host: uat.dmr.upstart.team
    http:
      paths:
      - path: /
        backend:
          serviceName: dmr-web
          servicePort: 80
