apiVersion: v1
kind: ConfigMap
metadata:
  name: env-app-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  COMMERCE_HOST: https://dmr-test-1-api.denvermattress-test.upstart.team
  REDIS_URL: redis://jx-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379
  DEBUG: "server:*"
  SITE_ROOT: "https://uat.dmr.upstart.team"
  GTM_ID: "GTM-KD5567J"
  RECAPTCHA_KEY: "6LeYNxgUAAAAACCJf24sS35GEhl1_RhM7Y9zf9fq"
  UPSTART_SITE: "8d3ea3bc-f65b-4227-9fa6-6fae40e4575a"
