dmr-web:
  replicaCount: 2
  tolerations:
  - effect: NoSchedule
    key: dmr-deployment-tier
    operator: Equal
    value: qa
  nodeSelector:
    cloud.google.com/gke-nodepool: qa-pool-beefier
redis:
  cluster:
    slaveCount: 1
  tolerations:
  - effect: NoSchedule
    key: dmr-deployment-tier
    operator: Equal
    value: qa
  nodeSelector:
    cloud.google.com/gke-nodepool: qa-pool-beefier
